/**
 * The matcher, against output from the real network.
 *
 * Every other test in this repository uses synthetic vectors: deterministic
 * noise that behaves like an embedding without being one. They prove the
 * plumbing. They cannot prove the thing the product actually claims — that two
 * photographs of one person land closer together than photographs of two
 * people — because a synthetic face is close to itself by construction.
 *
 * `real-faces.json` is what closes that gap. It is 17 descriptors produced by
 * the browser matcher in @rexell/ui from Creative Commons photographs of five
 * people, regenerated by `npm run face:calibrate` and then
 * `/fixture.html`. The photographs are not committed and are not needed: 128
 * numbers cannot be turned back into a face, which is the same reason the
 * product stores them instead of pictures.
 *
 * So these tests run on a machine with no camera, no browser and none of the
 * eight megabytes of weights, and still fail if the thresholds drift away from
 * the model — which is exactly how the old ones came to be wrong.
 */
import { describe, expect, it } from 'vitest';
import { PROTOTYPE_THRESHOLDS, band, similarity, toFaceVector } from '../src/index.js';
import faces from './real-faces.json' with { type: 'json' };

interface Face {
  person: string;
  photo: string;
  title: string;
  vector: number[];
}

const all = (faces as Face[]).map((f) => ({ ...f, v: toFaceVector(f.vector) }));
const pairs = all.flatMap((a, i) => all.slice(i + 1).map((b) => ({ a, b, score: similarity(a.v, b.v) })));
const genuine = pairs.filter((p) => p.a.person === p.b.person);
const impostor = pairs.filter((p) => p.a.person !== p.b.person);

describe('the matcher on real faces', () => {
  it('has a fixture worth trusting', () => {
    expect(all.length).toBeGreaterThanOrEqual(15);
    expect(new Set(all.map((f) => f.person)).size).toBeGreaterThanOrEqual(5);
    expect(genuine.length).toBeGreaterThanOrEqual(15);
    expect(impostor.length).toBeGreaterThanOrEqual(80);
    // Unit vectors, so similarity is a dot product and nothing downstream has
    // to divide by magnitudes it was never given.
    for (const f of all) expect(Math.hypot(...f.vector)).toBeCloseTo(1, 5);
  });

  it('scores two photographs of the same person above the match threshold', () => {
    const failures = genuine.filter((p) => p.score < PROTOTYPE_THRESHOLDS.match);
    expect(
      failures.map((p) => `${p.a.photo} vs ${p.b.photo} = ${p.score.toFixed(4)}`),
      'these are the same person and would be sent to the resolution desk',
    ).toEqual([]);
  });

  it('never scores two different people high enough to admit', () => {
    // This is the assertion with teeth. An impostor in the review band is a
    // referral to a human and costs throughput; an impostor at or above `match`
    // is a stranger walking in on somebody else's ticket, which nothing
    // downstream can catch.
    const admitted = impostor.filter((p) => p.score >= PROTOTYPE_THRESHOLDS.match);
    expect(
      admitted.map((p) => `${p.a.photo} vs ${p.b.photo} = ${p.score.toFixed(4)}`),
      'these are different people and would be admitted',
    ).toEqual([]);
  });

  it('keeps a real gap between the two distributions', () => {
    const worstGenuine = Math.min(...genuine.map((p) => p.score));
    const bestImpostor = Math.max(...impostor.map((p) => p.score));

    // The number that matters. On the raw descriptors, before the mean is
    // subtracted, this gap is 0.025 — the two distributions are technically
    // separable and practically touching, and any threshold between them is a
    // coin toss dressed up as a constant.
    expect(worstGenuine - bestImpostor).toBeGreaterThan(0.1);

    // And the decision band has to straddle that gap, or the thresholds are
    // describing some other model than the one that produced this fixture.
    expect(PROTOTYPE_THRESHOLDS.match).toBeLessThanOrEqual(worstGenuine);
    expect(PROTOTYPE_THRESHOLDS.match).toBeGreaterThan(bestImpostor);
  });

  it('bands every real pair as admit or not-admit, never the reverse', () => {
    for (const p of genuine) expect(band(p.score), `${p.a.photo} vs ${p.b.photo}`).toBe('match');
    for (const p of impostor) expect(band(p.score), `${p.a.photo} vs ${p.b.photo}`).not.toBe('match');

    // How many strangers land at the desk rather than being refused outright.
    // Not a failure, but it is the throughput cost of where `review` sits, and
    // it should be visible rather than discovered at a venue.
    const referred = impostor.filter((p) => band(p.score) === 'review');
    expect(referred.length / impostor.length).toBeLessThan(0.05);
  });

  it('picks the right person out of the whole gallery, not merely a close one', () => {
    // 1:N, which is what the gate actually does. Scoring well against your own
    // template is not enough if somebody else scores better.
    for (const probe of all) {
      const others = all.filter((f) => f.photo !== probe.photo);
      const best = others.reduce((x, y) => (similarity(probe.v, y.v) > similarity(probe.v, x.v) ? y : x));
      expect(best.person, `${probe.photo} was closest to ${best.photo}`).toBe(probe.person);
    }
  });
});
